### ISSUE TITLE
Does this plugin support monorepo ?

### ISSUE THREAD

**Issue by hyperse-net** [wetransform-os/gradle-semantic-release-version#49]
```
app
lib_core
lib_utils
```

auto resolve dependent version, and `semantic-release`

like this libraray https://github.com/changesets/changesets

**Comment by hyperse-net** [comment]
could you provider a completed git repo to demonstrate the `monorepo` example, or normal example 
which can automatically release to github `maven` , I believe it is very helpful for most people.

**Comment by stempler** [comment]
With `monorepo` I assume you mean having multiple projects in the same repository that each have their own different version?

I'm afraid that's currently not supported. I think this would require adding project specific prefixes for tags to determine the version for the related project, or something in that direction.

Right now this plugin will assume the same version for all projects within the repo.

**Comment by tianyingchun** [comment]
Can you provide an example using this plugin that targets single repositories published to GitHub maven,also Contain monorepo Release all the repositories in one go using the same version. Thank you very much. It has been configured for a long time without success

**Comment by stempler** [comment]
> Can you provide an example using this plugin that targets single repositories published to GitHub maven,also Contain monorepo Release all the repositories in one go using the same version.

Not sure what kind of example you are after exactly.

- [This repo itself](https://github.com/wetransform-os/gradle-semantic-release-version) is an example of a single project using this plugin and semantic-release
- [This repo](https://github.com/halestudio/hale-core) is an example where the plugin is [applied](https://github.com/halestudio/hale-core/blob/50787d6cdd8c62bdfdef777d36aef71372dccf19/buildSrc/src/main/groovy/hale.common.gradle#L2) for all projects to determine the version (same version for all projects) in combination with a [custom release workflow](https://github.com/halestudio/hale-core/blob/master/.github/workflows/release.yml) that internally uses semantic-release [via a custom action](https://github.com/wetransform/gha-workflows/blob/ac5514fee04f1b8ba18483fe8ff82c70fd134505/.github/workflows/gradle-library.yml#L209)

**Comment by hyperse-net** [comment]
thanks very much, i will try :)
